### ISSUE TITLE
[Question]: Disabling concrete-csprng warning 

### ISSUE THREAD

**Issue by pierreeliseeflory** [zama-ai/concrete-numpy#18]
Depending on the function evaluated using FHE, the following warning is printed multiple times per evaluation : 

> WARNING: You are currently using the software variant of `concrete-csprng` which does not have access to a hardware source of randomness. To ensure the security of your application, please arrange to provide a secret by using the `concrete_csprng::set_soft_rdseed_secret` function.

Is it possible to disable it when using the PyPi package `concrete-numpy` as it floods the notebook cells output ? I don't see any reference to a fix in the documentation.

**Comment by youben11** [comment]
Hi @pierreeliseeflory , the best course of action IMO is to solve the issue that's causing this instead of disabling it.

The hardware source of randomness not being found can be caused by two known issues:
- Using an old CPU which doesn't have that capability: I hope it's not your case, as this can't be solved
- You are on MacOS using a docker image: in this case, you just need to make sure the hardware features are available to the container

We can help with the second issue, but please let me know if you do have a totally different environment

**Comment by pierreeliseeflory** [comment]
Ok, this particular CPU was the problem as their was no such issue on another machine. Didn't think it could be the hardware since some functions (the tuto) didn't trigger the warnings but other could.

Thanks
